version: "3.4"

services:
  stackreverseproxy:
    image: stackreverseproxy
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production

  # docker-compose up --scale stackreverseproxy=3
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - stackreverseproxy
    ports:
      - 3006:3006
